src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 *  @UniqueEntity
 * (
 * fields={"title"},
 * message="Une autre annonce a déjà ce titre"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire au moins 10 caractères !", maxMessage="Le titre doit faire au plus 255 caratères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire au moins 20 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="La description doit faire au moins 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Initialise le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void 
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {

            $slugify =  new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }


    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation 
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // Calculer les jours qui sont entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            // Transformer $resultat en un tableau de vrai date de type DateTime
            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            // Fusion entre le tableau $notAvailableDays et $days
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    /**
     * Permet d'afficher la note moyenne de l'annonce
     *
     * @return float
     */
    public function getAvgRating()
    {
        // Calculé la somme des notations 
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        // Faire la division pour avoir la moyenne 
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * 
     * @return Comment | null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments  as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur s'est déjà inscrit avec cette adresse mail, merci de la modifier !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseignez un email valid")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une adresse mail valide pour votre avatar")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;


    /**
     *@Assert\EqualTo(propertyPath="hash", message="Votre mot de passe n'est pas le même")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caratères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Affiche le nom complet
     *
     * @return void
     */
    public function getFullName()
    {
        return "{$this->firstName} " . strtoupper("{$this->lastName}");
    }

    /**
     * Initialise le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void 
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {

            $slugify =  new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {

            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    { }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    { }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug' : ad.slug}) %}
<div class="col-md-4">
	<div class="card bg-light mb-3">
		<div class="card-header tex-center">
			{{ ad.rooms }}
			chambres,
			<strong>{{ ad.price  | number_format(2,',','')}} &euro; / nuit</strong><br>
			{% if ad.comments | length > 0 %}
				{% include "partials/rating.html.twig" with {'rating' : ad.avgRating} %}
			{% else %}
				<small>Pas encore noté</small>
			{% endif %}
		</div>
		<a href="{{ url }}">
			<img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height: 200px; width: 100%; display: block;">
		</a>
		<div class="card-body">
			<h4 class="card-title">
				<a href="{{ url }}">
					{{ ad.title }}
				</a>
			</h4>
			<p class="card-text">
				{{ ad.introduction }}
			</p>
			<a href="{{ url }}" class="btn btn-primary float-right">En savoir +</a>
			{% if app.user and app.user == ad.author %}

				<a href="{{ path('ads_edit', {'slug' : ad.slug }) }}" class="btn btn-secondary">Modifier l'annonce</a>
			{% endif %}
		</div>
	</div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_entry_row %}

	{{ form_widget(form) }}
{% endblock %}

{% block _ad_images_widget %}
	<p>Ici, vous pouvez ajouter d'autres images à l'annonce !</p>

	{{ form_widget(form) }}

	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-images" class="btn btn-primary">
			<i class="fas fa-plus"></i> 
			Ajouter une image
		</button>
	</div>
{% endblock %}

{% block _ad_images_entry_widget %}

	<div class="form-group" id="block_{{ id }}">
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification d'une annonce
{% endblock %}

{% form_theme form "ad/_collection.html.twig" %}
{% block body %}

	<div class="container">
		<h1>Modifier l'annonce:
			{{ ad.title }}</h1>

		{{ form_start(form) }}

		{{ form_widget(form) }}

		<button type="submit" class="btn btn-primary">Enregistrer</button>

		{{ form_end(form) }}
	</div>
{% endblock %}


{% block javascripts %}

	{{ encore_entry_script_tags('js/ad') }}
{% endblock %}

templates/ad/form_collections.html.twig
{% extends "base.html.twig" %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% form_theme form _self %}

{% block _ad_images_entry_row %}

	{{ form_widget(form) }}
{% endblock %}

{% block _ad_images_widget %}
	<p>Ici, vous pouvez ajouter d'autres images à l'annonce !</p>

	{{ form_widget(form) }}

	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-images" class="btn btn-primary">Ajouter une image</button>
	</div>
{% endblock %}

{% block _ad_images_entry_widget %}

	<div class="form-group" id="block_{{ id }}">
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script>
		$('#add-images').click(function () { // Je récupère le numéro des futurs champs que je vais créer
const index = +$('#widgets-counter').val();

// Je récupère le prototy des entrées
const tmpl = $('#ad_images').data('prototype').replace(/__name/g, index);

// J'injecte ce code au sein de la div
$('#ad_images').append(tmpl);

$('#widgets-counter').val(index+1);

// Je gère le button supprimer
handleDeleteButtons();
});

function handleDeleteButtons() {
$('button[data-action="delete"]').click(function () {
const target = this.dataset.target;
$(target).remove();

});
}

handleDeleteButtons();
	</script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces
{% endblock %}

{% block body %}

	<div class="container">
		<h1 class="my-35">Voicis les annonces des hôtes !</h1>

		<div class="row">
			{% for ad in ads %}
			{% include "ad/_ad.html.twig" %}
			{% endfor %}
		</div>
	</div>

{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce
{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% form_theme form "ad/_collection.html.twig" %}

{% block body %}

	<div class="container">
		<h1>Créer une nouvelle annonce</h1>

		{{ form_start(form) }}

		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Informations générales</h2>
					<hr>
					{{ form_row(form.title) }}
					{{ form_row(form.slug) }}
					{{ form_row(form.price) }}
					{{ form_row(form.rooms) }}
				</div>

				<div class="alert alert-light">
					<h2>Détails de l'annonce</h2>
					<hr>
					{{ form_row(form.introduction) }}
					{{ form_row(form.content) }}
				</div>
			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2>Image de l'annonce</h2>
					<hr>
					{{ form_row(form.coverImage) }}
					{{ form_row(form.images) }}
				</div>
			</div>
		</div>

		<div class="alert alert-success clearfix">
			<h2 class="alert-heading">Sauvegarder mon annonce</h2>
			<p>Vous êtes sur le point de créer votre d'annonce, nous sommes fière de vous !</p>
			<button type="submit" class="btn btn-primary float-right">
				<i class="fas fa-check"></i>
				Créer la nouvelle annonce
			</button>
		</div>


		{{ form_end(form) }}
	</div>
{% endblock %}

{% block javascripts %}

	{{ encore_entry_script_tags('js/ad') }}
{% endblock %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ ad.title }}
{% endblock %}

{% block body %}

	<div class="new-title" style=" background-image: url({{ ad.coverImage }});">

		<div class="container">
			<h1>{{ ad.title }}</h1>

			<p>{{ ad.introduction }}</p>

			<p class="h2">
				<strong>{{ ad.rooms }}
					chambre(s)</strong>
				pour
				<strong>{{ad.price | number_format(2,',','')}} &euro; / nuit</strong>
			</p>
			<a href="{{ path('booking_create', {'slug' : ad.slug}) }}" class="btn btn-primary">Reserver !</a>
			{% if app.user and app.user == ad.author %}

				<a href="{{ path('ads_edit', {'slug' : ad.slug }) }}" class="btn btn-secondary">Modifier l'annonce</a>
				<a href="{{ path('ads_delete', {'slug' : ad.slug}) }}" onclick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce: {{ ad.title }} ?`)" class="btn btn-danger">Supprimer l'annonce</a>
			{% endif %}
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				{{ ad.content | raw }}

				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						{% for image in ad.images %}
							<li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active {% endif %}"></li>
						{% endfor %}
					</ol>
					<div class="carousel-inner">

						{% for image in ad.images %}
							<div class="carousel-item {% if loop.first %} active {% endif %}">
								<img src="{{ image.url }}" class="d-block w-100" alt="...">
								<div class="carousel-caption d-none d-md-block">
									<h5>{{ ad.title }}</h5>
									<p>{{ image.caption }}</p>
								</div>
							</div>
						{% endfor %}
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>

				<hr>

				{% if ad.comments | length > 0  %}
					<h2 class="mb-3">Commentaires de nos voyageurs:</h2>

					<div class="alert alert-info">
						<h4 class="amert-heading text-center ">
							<div class="row align-items-center">
								<div class="col" style="color: black;">
									Note globale donnée par nos voyageurs
								</div>
								<div class="col">
									{% include "partials/rating.html.twig" with{'rating' : ad.avgRating} %}
									<br>
									<small>
										(Calculé sur
										{{ ad.comments | length }}
										avis !)
									</small>
								</div>
							</div>
						</h4>
					</div>

					{% for comment in ad.comments %}
						<div class="rounded mb-3 py-3 px-3" style=" background-color: rgba(21,140,186, 0.05)">
							<strong>{{ comment.author.firstName }}
								a dit:</strong>
							<blockquote>
								{{ comment.content }}
							</blockquote>

							<strong>Note données:</strong>
							{% include "partials/rating.html.twig" with {'rating' : comment.rating} %}
						</div>
					{% endfor %}
				{% else %}
					<h2>Cette annonce n'a pas encore reçu de commentaires</h2>
				{% endif %}

			</div>
			<div class="col">

				{% set author = ad.author %}
				<div class="row">
					<div class="col-3">
						<a href="{{ path('user_show', {'slug' : author.slug}) }}">
							<img src="{{ author.picture }}" class="avatar avatar-medium" alt="avatar de {{ author.fullName }}">
						</a>
					</div>
					<div class="col">
						<a href="{{ path('user_show', {'slug' : author.slug}) }}">
							<h3>{{ author.fullName }}</h3>
						</a>
						<span class="badge badge-primary">{{ author.ads | length }}
							annonces</span>
						<p>{{ author.description | raw }}</p>
					</div>
				</div>

			</div>
		</div>
	</div>

{% endblock %}